# 服务器配置
server:
  host: "0.0.0.0"  # 监听地址
  port: 8080  # 监听端口
  debug: false  # 调试模式
  reload: false  # 自动重载
  workers: 1  # 工作进程数

# 数据库配置
database:
  # 数据库类型: sqlite 或 mysql
  type: "sqlite"
  
  # SQLite配置（默认）
  sqlite:
    path: "./data/app.db"
  
  # MySQL配置（可选）
  mysql:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3306}"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD}"
    database: "${MYSQL_DATABASE:ai_doc_test}"
    charset: "utf8mb4"
    # 连接池配置
    pool:
      pool_size: 5
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 3600
      pool_pre_ping: true

# AI模型配置 - 支持多模型
ai_models:
  # 默认使用的模型索引（从0开始）
  default_index: 0
  
  # 模型列表
  models:
    - label: "GPT-4o Mini (快速)"  # 前端显示名称
      provider: "openai"
      config:
        api_key: "${OPENAI_API_KEY}"  # 从环境变量获取
        base_url: "https://api.openai.com/v1"
        model: "gpt-4o-mini"
        temperature: 0.3
        max_tokens: 8000
        context_window: 128000  # 模型的上下文窗口大小
        reserved_tokens: 2000    # 预留给系统提示词的tokens
        timeout: 12000
        max_retries: 3
      description: "适合快速处理，成本较低"
      
    - label: "GPT-3.5 Turbo (备用)"  # 前端显示名称
      provider: "openai"
      config:
        api_key: ${OPENAI_API_KEY}
        base_url: "https://api.openai.com/v1"
        model: "gpt-3.5-turbo"
        temperature: 0.5
        max_tokens: 4096
        context_window: 16000   # 模型的上下文窗口大小
        reserved_tokens: 1500    # 预留给系统提示词的tokens
        timeout: 30
        max_retries: 2
      description: "备用模型，成本和性能平衡"

# 文件设置  
file_settings:
  max_file_size: 10485760  # 10MB
  chunk_size: 8000  # 文本分块大小（废弃，改为从模型配置动态计算）
  allowed_extensions:
    - pdf
    - docx
    - md
    - txt

# 目录配置
directories:
  upload_dir: ./data/uploads
  report_dir: ./data/reports
  log_dir: ./data/logs
  temp_dir: ./data/temp

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./data/logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# 任务处理配置
task_processing:
  max_concurrent_tasks: 3  # 最大并发任务数
  task_timeout: 12000  # 任务超时时间（秒）
  retry_failed_tasks: true  # 是否重试失败的任务
  
  # 章节合并配置
  section_merge:
    enabled: true  # 是否启用章节合并
    max_chars: 5000  # 合并后章节最大字符数
    min_chars: 100  # 最小章节字符数（短于此数值的章节总是被合并）
    preserve_structure: true  # 是否保持章节层级结构
  
# CORS配置
cors:
  enabled: true
  origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:3002"
    - "http://localhost:3003"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# 环境变量映射（可选）
env_mapping:
  OPENAI_API_KEY: "OPENAI_API_KEY"
  ANTHROPIC_API_KEY: "ANTHROPIC_AUTH_TOKEN"
  ANTHROPIC_BASE_URL: "ANTHROPIC_BASE_URL"