# 数据库
database: ./data/app.db

# AI服务配置
ai_service:
  # 模型提供商：openai, anthropic, azure, custom
  provider: "openai"
  
  # OpenAI配置
  openai:
    api_key: "${OPENAI_API_KEY}"  # 从环境变量获取，或直接填写
    base_url: "https://api.openai.com/v1"  # API端点，可自定义
    model: "gpt-4o-mini"  # 使用的模型
    temperature: 0.3  # 温度参数，控制创造性
    max_tokens: 4096  # 最大token数
    timeout: 30  # 请求超时时间（秒）
    max_retries: 3  # 最大重试次数
    
  # Anthropic配置（备选）
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"  # 从环境变量获取
    base_url: "${ANTHROPIC_BASE_URL}"  # 自定义端点
    model: "claude-3-haiku-20240307"  # 使用的模型
    temperature: 0.3
    max_tokens: 4096
    timeout: 30
    max_retries: 3
    
  # 通用配置
  default:
    temperature: 0.3
    max_tokens: 4096
    timeout: 30
    max_retries: 3
    
  # 降级策略
  fallback:
    enabled: true  # 是否启用降级
    provider: "anthropic"  # 降级到的提供商
    

# 文件设置  
max_file_size: 10485760  # 10MB
chunk_size: 8000

# 目录
upload_dir: ./data/uploads
report_dir: ./data/reports