# 测试配置文件
server:
  host: "127.0.0.1"
  port: 8081  # 不同的端口
  debug: true
  reload: false
  workers: 1

# AI模型配置 - 测试环境
ai_models:
  default_index: 1  # 不同的默认模型
  
  models:
    - label: "测试模型1"
      provider: "openai"
      config:
        api_key: "test-key-1"
        base_url: "https://api.test1.com/v1"
        model: "test-model-1"
        temperature: 0.5
        max_tokens: 2048
        timeout: 60
        max_retries: 2
      description: "第一个测试模型"
      
    - label: "测试模型2 (默认)"
      provider: "anthropic"
      config:
        api_key: "test-key-2"
        base_url: "https://api.test2.com/v1"
        model: "test-model-2"
        temperature: 0.2
        max_tokens: 4096
        timeout: 30
        max_retries: 1
      description: "第二个测试模型，设为默认"

# 其他配置保持简单
file_settings:
  max_file_size: 5242880  # 5MB
  chunk_size: 4000
  allowed_extensions:
    - md
    - txt

directories:
  upload_dir: ./data/test_uploads
  report_dir: ./data/test_reports
  log_dir: ./data/test_logs
  temp_dir: ./data/test_temp

cors:
  enabled: true
  origins:
    - "http://localhost:3004"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]